---
fee_config:
  marinade_fee_bps: 950
  marinade:
    stake_authority: BBaQsiRo744NAYaqL3nKRfgeJayoqVicEQsEnLpfsJ6x
    withdraw_authority: BBaQsiRo744NAYaqL3nKRfgeJayoqVicEQsEnLpfsJ6x
  dao:
    fee_split_share_bps: 10000
    stake_authority: mDAo14E6YJfEHcVZLcc235RVjviypmKMhftq7jeiLJz
    withdraw_authority: mDAo14E6YJfEHcVZLcc235RVjviypmKMhftq7jeiLJz

whitelist_stake_authorities:
  - stWirqFCf2Uts1JBL1Jsd3r6VBWhgnpdPxCTe1MFjrq
  - 4bZ6o3eUUNXhKuqjdCnCoPAoLgWiuLYixKaxoa8PpiKk
  - ex9CfkBZZd6Nv9XdnoDmmB45ymbu4arXVk7g5pWnt3N

settlements:
  - Bidding:
      meta:
        funder: ValidatorBond

  - BidTooLowPenalty:
      meta:
        funder: ValidatorBond

  - BlacklistPenalty:
      meta:
        funder: ValidatorBond

  # PSR - Validator funded (0-50% loss)
  - DowntimeRevenueImpactSettlement:
      meta:
        funder: ValidatorBond
      min_settlement_lamports: 100000000 # 0.1 SOL
      grace_downtime_bps: 100 # 1 %
      covered_range_bps: [0, 5000] # 0 % - 50 %

  # PSR - Marinade funded (50-100% loss)
  - DowntimeRevenueImpactSettlement:
      meta:
        funder: Marinade
      min_settlement_lamports: 100000000 # 0.1 SOL
      covered_range_bps: [5000, 10000] # 50 % - 100 %

  - CommissionSamIncreaseSettlement:
      meta:
        funder: ValidatorBond
      min_settlement_lamports: 10000000 # 0.01 SOL
      grace_increase_bps: 100 # 1 %
      covered_range_bps: [0, 10000] # 0 % - 100 %
      extra_penalty_threshold_bps: 700 # 7%
      base_markup_bps: 1000 # 10%
      penalty_markup_bps: 10000 # 100%
